"""add GIS parcel and spatial validation tables

Revision ID: 0406b1ae86d4
Revises: 13745b9b6e54
Create Date: 2026-08-26 12:17:24.219344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.parcel



# revision identifiers, used by Alembic.
revision: str = '0406b1ae86d4'
down_revision: Union[str, Sequence[str], None] = '13745b9b6e54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_number', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('taluk', sa.String(length=100), nullable=False),
    sa.Column('village', sa.String(length=100), nullable=False),
    sa.Column('area_sq_m', sa.Float(), nullable=False),
    sa.Column('geometry', app.models.parcel.CompatibleGeometry(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcels_survey_number'), 'parcels', ['survey_number'], unique=False)
    op.create_table('spatial_validations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('parcel_id', sa.Integer(), nullable=True),
    sa.Column('geometry_valid', sa.Boolean(), nullable=False),
    sa.Column('overlap_detected', sa.Boolean(), nullable=False),
    sa.Column('overlap_area_sq_m', sa.Float(), nullable=False),
    sa.Column('overlap_percentage', sa.Float(), nullable=False),
    sa.Column('area_difference_percent', sa.Float(), nullable=True),
    sa.Column('spatial_relationship', sa.String(length=50), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('algorithm_version', sa.String(length=50), nullable=False),
    sa.Column('dataset_version', sa.String(length=50), nullable=False),
    sa.Column('crs', sa.String(length=50), nullable=False),
    sa.Column('candidate_geojson', sa.Text(), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spatial_validations_document_id'), 'spatial_validations', ['document_id'], unique=False)
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='unique')
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=False)
    op.drop_index(op.f('ix_spatial_validations_document_id'), table_name='spatial_validations')
    op.drop_table('spatial_validations')
    op.drop_index(op.f('ix_parcels_survey_number'), table_name='parcels')
    op.drop_table('parcels')
    # ### end Alembic commands ###
