"""add OCR extraction tables

Revision ID: 13745b9b6e54
Revises: f8dc7b297149
Create Date: 2026-08-26 12:05:11.368029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13745b9b6e54'
down_revision: Union[str, Sequence[str], None] = 'f8dc7b297149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocr_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_fields_document_id'), 'ocr_fields', ['document_id'], unique=False)
    op.create_table('ocr_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('raw_blocks', sa.JSON(), nullable=False),
    sa.Column('engine', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_results_document_id'), 'ocr_results', ['document_id'], unique=False)
    with op.batch_alter_table('documents') as batch_op:
        batch_op.alter_column('file_hash',
                   existing_type=sa.VARCHAR(length=64),
                   nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='unique')
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=False)
    op.alter_column('documents', 'file_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_index(op.f('ix_ocr_results_document_id'), table_name='ocr_results')
    op.drop_table('ocr_results')
    op.drop_index(op.f('ix_ocr_fields_document_id'), table_name='ocr_fields')
    op.drop_table('ocr_fields')
    # ### end Alembic commands ###
