"""add zk proof and blockchain anchor tables

Revision ID: 48f0283dcbbc
Revises: def583e5add1
Create Date: 2026-08-26 12:47:28.542747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48f0283dcbbc'
down_revision: Union[str, Sequence[str], None] = 'def583e5add1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blockchain_anchors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('verification_id', sa.String(length=100), nullable=False),
    sa.Column('transaction_hash', sa.String(length=100), nullable=True),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('contract_address', sa.String(length=100), nullable=False),
    sa.Column('network', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id'),
    sa.UniqueConstraint('verification_id')
    )
    op.create_table('zk_proof_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proof_id', sa.String(length=100), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('commitment', sa.String(length=100), nullable=False),
    sa.Column('public_signals', sa.Text(), nullable=False),
    sa.Column('proof_json', sa.Text(), nullable=False),
    sa.Column('circuit_version', sa.String(length=50), nullable=False),
    sa.Column('verification_key_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zk_proof_records_document_id'), 'zk_proof_records', ['document_id'], unique=False)
    op.create_index(op.f('ix_zk_proof_records_proof_id'), 'zk_proof_records', ['proof_id'], unique=True)
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='unique')
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=False)
    op.drop_index(op.f('ix_zk_proof_records_proof_id'), table_name='zk_proof_records')
    op.drop_index(op.f('ix_zk_proof_records_document_id'), table_name='zk_proof_records')
    op.drop_table('zk_proof_records')
    op.drop_table('blockchain_anchors')
    # ### end Alembic commands ###
