"""add verification orchestration fields

Revision ID: 49e4b1967d18
Revises: 76e46ab2965f
Create Date: 2026-08-26 13:53:59.162143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49e4b1967d18'
down_revision: Union[str, Sequence[str], None] = '76e46ab2965f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('verifications', sa.Column('current_stage', sa.String(length=50), nullable=True, server_default='DOCUMENT'))
    op.add_column('verifications', sa.Column('stages_json', sa.JSON(), nullable=True))
    op.add_column('verifications', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('verifications', sa.Column('review_required', sa.Boolean(), nullable=True, server_default='0'))
    op.add_column('verifications', sa.Column('review_reason', sa.Text(), nullable=True))
    op.add_column('verifications', sa.Column('reviewed_by', sa.Integer(), nullable=True))
    op.add_column('verifications', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('verifications', sa.Column('review_decision', sa.String(length=30), nullable=True))
    op.add_column('verifications', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_verifications_status'), 'verifications', ['status'], unique=False)

    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verifications', type_='foreignkey')
    op.drop_constraint(None, 'verifications', type_='foreignkey')
    op.create_foreign_key(None, 'verifications', 'documents', ['document_id'], ['id'])
    op.drop_constraint(None, 'verifications', type_='unique')
    op.drop_index(op.f('ix_verifications_status'), table_name='verifications')
    op.alter_column('verifications', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('verifications', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('verifications', 'updated_at')
    op.drop_column('verifications', 'review_decision')
    op.drop_column('verifications', 'reviewed_at')
    op.drop_column('verifications', 'reviewed_by')
    op.drop_column('verifications', 'review_reason')
    op.drop_column('verifications', 'review_required')
    op.drop_column('verifications', 'error_message')
    op.drop_column('verifications', 'stages_json')
    op.drop_column('verifications', 'current_stage')
    op.drop_constraint(None, 'documents', type_='unique')
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=False)
    # ### end Alembic commands ###
