"""add document storage and processing jobs

Revision ID: f8dc7b297149
Revises: 6b9d6b2d7b6c
Create Date: 2026-08-26 11:52:45.361520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8dc7b297149'
down_revision: Union[str, Sequence[str], None] = '6b9d6b2d7b6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_document_id'), 'processing_jobs', ['document_id'], unique=False)
    with op.batch_alter_table('documents') as batch_op:
        batch_op.add_column(sa.Column('owner_user_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('storage_key', sa.String(length=500), server_default='legacy', nullable=False))
        batch_op.add_column(sa.Column('sha256', sa.String(length=64), server_default='legacy', nullable=False))
        batch_op.add_column(sa.Column('status', sa.Enum('UPLOADED', 'VALIDATING', 'STORED', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', 'REJECTED', name='documentstatus'), server_default='STORED', nullable=False))
        batch_op.add_column(sa.Column('version', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.alter_column('mime_type',
                   existing_type=sa.VARCHAR(length=100),
                   nullable=False)
        batch_op.alter_column('file_size',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   nullable=False)
        batch_op.alter_column('verification_id',
                   existing_type=sa.VARCHAR(length=100),
                   nullable=True)
        batch_op.alter_column('file_path',
                   existing_type=sa.VARCHAR(length=500),
                   nullable=True)
        batch_op.alter_column('created_at',
                   existing_type=sa.DATETIME(),
                   nullable=False)
        batch_op.create_index('ix_documents_owner_user_id', ['owner_user_id'], unique=False)
        batch_op.create_index('ix_documents_sha256', ['sha256'], unique=False)
        batch_op.create_foreign_key('fk_documents_owner_user_id', 'users', ['owner_user_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_hash', sa.VARCHAR(length=64), nullable=False))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='unique')
    op.drop_index(op.f('ix_documents_sha256'), table_name='documents')
    op.drop_index(op.f('ix_documents_owner_user_id'), table_name='documents')
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=False)
    op.alter_column('documents', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('documents', 'file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('documents', 'verification_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('documents', 'file_size',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('documents', 'mime_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'version')
    op.drop_column('documents', 'status')
    op.drop_column('documents', 'sha256')
    op.drop_column('documents', 'storage_key')
    op.drop_column('documents', 'owner_user_id')
    op.drop_index(op.f('ix_processing_jobs_document_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    # ### end Alembic commands ###
